version: "3.7"
services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      IMAGES: 1
      INFO: 1
      STATS: 1
      EVENTS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375" # Expose port to host

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    # network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDKzBXCwJ3T1w7MS1dE35M5JnIwe/kHvizoHGtvzSzw"
      SERVER: "https://beszel.dnaone.love/"
    ports:
      - "45876:45876" # Expose port to host
    networks:
      - pi-server_net

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: always
    pid: "host"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${USERDIR}/glances/glances.conf:/glances/conf/glances.conf"
    ports:
      - "61208:61208"
    environment:
      - GLANCES_ENABLE_SENSORS=true
    networks:
      - pi-server_net
    command: glances -C /glances/conf/glances.conf -w

  ######### PERSONAL VIDEO RECORDERS ##########
  # Wake-On-Lan
  pi-wol:
    image: chtake/pi-wol:latest
    container_name: pi-wol
    hostname: pi-wol
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: always
    volumes:
      - ${USERDIR}/pi-wol/data:/app/data
      - ./dataprotection-keys:/root/.aspnet/DataProtection-Keys
    ports:
      - 8880:8080
    networks:
      - pi-server_net

  # Radarr – Movie Download and Management
  radarr:
    image: "linuxserver/radarr"
    hostname: radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/radarr/config:/config
      - ${USERDIR}/transmission/downloads:/home/downloads
      - /mnt/usb/watch:/home/watch
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 7878:7878
    restart: always
    networks:
      - pi-server_net

  # Sonarr – TV Show Download and Management
  sonarr:
    image: "linuxserver/sonarr"
    hostname: sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/sonarr/config:/config
      - /mnt/usb/watch:/home/watch
      - ${USERDIR}/transmission/downloads:/home/downloads
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 8989:8989
    restart: always
    networks:
      - pi-server_net

  # Overseerr – Accept Requests for your Media Server
  overseerr:
    hostname: overseerr
    restart: always
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/overseerr/config:/config
      - ${USERDIR}/transmission/downloads:/home/downloads
      - /mnt/usb/watch:/home/watch
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 5055:5055
    networks:
      - pi-server_net

  # prowlarr – Torrent Proxy
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - pi-server_net

  ######### DOWNLOADERS ##########

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    hostname: transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - TRANSMISSION_WEB_HOME= /usr/share/transmission/web
    #      - USER= #optional
    #      - PASS= #optional
    #      - WHITELIST= #optional
    #      - PEERPORT= #optional
    #      - HOST_WHITELIST= #optional
    volumes:
      - ${USERDIR}/transmission/config:/config
      - ${USERDIR}/transmission/downloads:/downloads
      - /mnt/usb/watch:/home/watch
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - pi-server_net

networks:
  pi-server_net:
    driver: bridge
