version: "3.7"
services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-socket-proxy
    environment:
      CONTAINERS: 1
      IMAGES: 1
      INFO: 1
      STATS: 1
      EVENTS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: ${SSH_KEY}
      SERVER: "https://beszel.dnaone.love/"

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    # ports:
    #   - "8070:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://192.168.50.201:2375 # Use host IP for docker-socket-proxy
    depends_on:
      - docker-socket-proxy

  ######### PERSONAL VIDEO RECORDERS ##########
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # Wake-On-Lan
  pi-wol:
    image: chtake/pi-wol:latest
    container_name: pi-wol
    hostname: pi-wol
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: always
    volumes:
      - ${USERDIR}/pi-wol/data:/app/data
    ports:
      - 8080:8080
    network_mode: "host"

  # Radarr – Movie Download and Management
  radarr:
    image: "linuxserver/radarr"
    hostname: radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/radarr/config:/config
      - ${USERDIR}/transmission/downloads:/home/downloads
      - /mnt/usb/watch:/home/watch
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 7878:7878
    restart: always

  # Sonarr – TV Show Download and Management
  sonarr:
    image: "linuxserver/sonarr"
    hostname: sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/sonarr/config:/config
      - /mnt/usb/watch:/home/watch
      - ${USERDIR}/transmission/downloads:/home/downloads
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 8989:8989
    restart: always

  # Overseerr – Accept Requests for your Media Server
  overseerr:
    hostname: overseerr
    restart: always
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/overseerr/config:/config
      - ${USERDIR}/transmission/downloads:/home/downloads
      - /mnt/usb/watch:/home/watch
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 5055:5055

  # prowlarr – Torrent Proxy
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  ######### DOWNLOADERS ##########

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    hostname: transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    #      - TRANSMISSION_WEB_HOME= /transmission
    #      - USER= #optional
    #      - PASS= #optional
    #      - WHITELIST= #optional
    #      - PEERPORT= #optional
    #      - HOST_WHITELIST= #optional
    volumes:
      - ${USERDIR}/transmission/config:/config
      - ${USERDIR}/transmission/downloads:/downloads
      - /mnt/usb/watch:/home/watch
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
