version: "3.7"
services:
  ######### PERSONAL VIDEO RECORDERS ##########
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # Wake-On-Lan
  pi-wol:
    image: chtake/pi-wol:latest
    container_name: pi-wol
    hostname: pi-wol
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: always
    volumes:
      - ${USERDIR}/pi-wol/data:/app/data
    ports:
      - 8080:8080
    network_mode: "host"

  # Radarr – Movie Download and Management
  radarr:
    image: "linuxserver/radarr"
    hostname: radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/radarr/config:/config
      - ${USERDIR}/transmission/downloads:/home/downloads
      - /mnt/usb/watch:/home/watch
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 7878:7878
    restart: always

  # Sonarr – TV Show Download and Management
  sonarr:
    image: "linuxserver/sonarr"
    hostname: sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/sonarr/config:/config
      - /mnt/usb/watch:/home/watch
      - ${USERDIR}/transmission/downloads:/home/downloads
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 8989:8989
    restart: always

  # Overseerr – Accept Requests for your Media Server
  overseerr:
    hostname: overseerr
    restart: always
    image: linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/overseerr/config:/config
      - ${USERDIR}/transmission/downloads:/home/downloads
      - /mnt/usb/watch:/home/watch
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 5055:5055

  # prowlarr – Torrent Proxy
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  ######### DOWNLOADERS ##########

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    hostname: transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    #      - TRANSMISSION_WEB_HOME= /transmission
    #      - USER= #optional
    #      - PASS= #optional
    #      - WHITELIST= #optional
    #      - PEERPORT= #optional
    #      - HOST_WHITELIST= #optional
    volumes:
      - ${USERDIR}/transmission/config:/config
      - ${USERDIR}/transmission/downloads:/downloads
      - /mnt/usb/watch:/home/watch
      - ${ASUSDIR}/current.shows:/home/current.shows
      - ${ASUSDIR}/movies.latest:/home/movies.latest
      - ${ASUSDIR}/movies.angie:/home/movies.angie
      - ${ASUSDIR}/movies.collection:/home/movies.collection
      - ${ASUSDIR}/sna.movies:/home/sna.movies
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
